apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding
resources:
  - ../../base/linkding/
  - database.yaml
  - linkding-container-env-secret.yaml
  - linkding-db-secret.yaml
  - ingress.yaml
patchesStrategicMerge:
  - deployment-postgres-patch.yaml
