apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
data:
  services.yaml: |
    - Bookmarks:
        - Linkding:
            icon: linkding.png
            href: https://linkding.staging.ronaldlokers.nl
            description: Bookmark manager

    - Reading:
        - Commafeed:
            icon: commafeed.png
            href: https://commafeed.staging.ronaldlokers.nl
            description: RSS feed reader

    - Health:
        - Nightscout:
            icon: nightscout.png
            href: https://nightscout.staging.ronaldlokers.nl
            description: CGM remote monitoring

    - Photos:
        - Immich:
            icon: immich.png
            href: https://immich.staging.ronaldlokers.nl
            description: Photo management
            widget:
              type: immich
              url: https://immich.staging.ronaldlokers.nl
              key: qvnCcXWT9a8SShkZCHvtgCl3SW9Ta6QLcuCBTqJD94
              version: 2
    - Monitoring:
        - Grafana:
            icon: grafana.png
            href: https://grafana.staging.ronaldlokers.nl
            description: Metrics and dashboards
            widget:
              type: grafana
              url: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80
              username: "{{HOMEPAGE_VAR_GRAFANA_USER}}"
              password: "{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}"

    - GitOps:
        - Flux:
            icon: flux-cd.png
            href: https://fluxcd.io/
            description: GitOps continuous delivery
  proxmox.yaml: ""
