apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - ../../base/immich
  - immich-library-pv.yaml
  - ingress.yaml
  - immich-db-secret.yaml
patches:
  - path: pvc-patch.yaml
    target:
      kind: PersistentVolumeClaim
      name: immich-model-cache
