apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  values:
    "machine-learning":
      persistence:
        cache:
          storageClass: local-path
          accessMode: ReadWriteOnce
