apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik-podmonitor.yaml
  - cert-manager-servicemonitors.yaml
  - metallb-podmonitors.yaml
  - flux-podmonitors.yaml
  - cloudnativepg-podmonitors.yaml
  - speedtest-servicemonitor.yaml
