apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nightscout
resources:
  - ../../base/nightscout/
  - nightscout-env-secret.yaml
  - ferretdb-postgres-secret.yaml
  - ingress.yaml
patchesStrategicMerge:
  - deployment-patch.yaml
