apiVersion: apps/v1
kind: Deployment
metadata:
  name: commafeed
spec:
  template:
    spec:
      containers:
        - name: commafeed
          env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: "jdbc:postgresql://postgres-cluster-rw.database.svc.cluster.local/commafeed"
            - name: QUARKUS_DATASOURCE_USERNAME
              value: "app"
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: ""
