apiVersion: apps/v1
kind: Deployment
metadata:
  name: commafeed
spec:
  template:
    spec:
      containers:
        - name: commafeed
          env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              valueFrom:
                secretKeyRef:
                  name: commafeed-db-secret
                  key: QUARKUS_DATASOURCE_JDBC_URL
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: commafeed-db-secret
                  key: QUARKUS_DATASOURCE_USERNAME
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: commafeed-db-secret
                  key: QUARKUS_DATASOURCE_PASSWORD
