apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: commafeed
resources:
  - ../../base/commafeed/
  - ingress.yaml
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: commafeed
