apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:UZa0gBmAM0Kp8q1mFmYnS90Ifiw+DzaoVz/f837Dm8z80GPS6jyQ6Q==,iv:z4oBr+eZzEYEiK3wcxmCSLg5jvNGSsoKBsednXgZMkc=,tag:pQKhlLmZ0p3idrB/G493og==,type:str]
sops:
    age:
        - recipient: age1uq9nturwsx36q045qtrm85lkg8qmzpgk9srduqesxs2ahjurw53sp9rhm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQzEvV3NubjhMejlVcWN1
            ME0xaHpaeUpzck9SSlR1Q3lRaUQ0bFZpSVgwCjc1ZEJMdFpQSVp4SGE2OFI4eWxk
            VmxJRjlIWEkxalpBeXRnZk5Sek5Ha0kKLS0tIHdYcDlmL2duUUNGRTBSUElUdit3
            YWNIaDQ5K2UyNDY3NDZHKzZSd21VeXMK6/loAYGGZl7Fuvs/5OMTWMTItloZSzrM
            jVw8UjIqvrEylXUvb2tCjAAb86s3ztzYIy2qti+QbHVy+dUWrRljEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-02T15:07:45Z"
    mac: ENC[AES256_GCM,data:Bduk3IX5mGrbKdFP3Wwwi4h3S+GaSD/RBqhZsGHFohF/NQDJbNbIRtU4EbRWfQiXGXm2z2G44SxSZ6n5gVnRqjSNLJm+qYtumGeJtO0MV9eXvkANam+QGodMqm4lcmdIHHQnhPEomLL44/ukbuFTEgnd7gdOj7Cnv3V/uspnwKA=,iv:VmG8LAPh90NM1YwpI4Um+D2p7V7wEFGNVOa7RTtPGOg=,tag:YZKkbL7/Ux3bF3jjH5QeUQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
