apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-staging-ronaldlokers-nl
  namespace: kube-system
spec:
  secretName: wildcard-staging-ronaldlokers-nl-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - "*.staging.ronaldlokers.nl"
