apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:Myr+20juoE/j61fehH3pmFBYSb4mlPSoYPtOuGLFazDd8jqWkwrjsQ==,iv:t5iCORsG7yGlUUJw6drjqz8+DYkvrWvWhlMSSFpfYBE=,tag:GbtFJbN8VZPBfFaINBhYiQ==,type:str]
sops:
    age:
        - recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTmMxKzhpUGprb2p4dTIz
            UjEzM2VXWkJkR3E5Z1l5Vk1ZQkJHMUM3YTBVCmltNWZvdC9KWXVEV2FNSzdRSmI0
            cEJZSDg5RS9KbGQ1WFJiaUc4K3FHbFkKLS0tIGJqQjBlbFplWSs4WWYvejdsWk1R
            YWR6dUNMWXlMTnZwOThLNzNWV2diU1UK0ZOCwA7dm7IprL5LSE/ib/jqq0BF43Cc
            3mUBOENZNW3BDZjFwtKbnXeNoX7M3tdB/8MFjdRZ07+kzXCU3P1E6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T15:12:12Z"
    mac: ENC[AES256_GCM,data:E7fbgdW2fME9v1GnOfixNHO9XGmIu2tIG3de0Gpy1W4MQbcPkzHUrPZSQ5tE+3eIm5uAEletC5xnruJ0uYolZyFQZBtAu6MBSbQjH9eMZdjTIBe77C+qnuzWJL4bP7n0Buix6PnnunB7WQuHwoLEPtFXR2nu8DkMy14dHRxO0JM=,iv:GWGsLWP+Dg3FBpDhPQ08AmG9Txa8bwz8eP0jGoLzaFE=,tag:0ybhT7VkEy0WXwYtNN0+2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
