apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-ronaldlokers-nl
  namespace: kube-system
spec:
  secretName: wildcard-ronaldlokers-nl-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "*.ronaldlokers.nl"
