apiVersion: apps/v1
kind: Deployment
metadata:
  name: ferretdb
  namespace: nightscout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ferretdb
  template:
    metadata:
      labels:
        app: ferretdb
    spec:
      containers:
        - name: ferretdb
          image: ghcr.io/ferretdb/ferretdb:2.1.0
          ports:
            - containerPort: 27017
              name: mongodb
          env:
            - name: FERRETDB_TELEMETRY
              value: "disable"
---
apiVersion: v1
kind: Service
metadata:
  name: ferretdb
  namespace: nightscout
spec:
  selector:
    app: ferretdb
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
