apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pgadmin
resources:
  - ../../base/pgadmin/
  - pgadmin-credentials-secret.yaml
  - pgadmin-servers-secret.yaml
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: pgadmin4
