apiVersion: v1
kind: Secret
metadata:
    name: b2-credentials
    namespace: database
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:sDauquygYkZvwCFyqh/UxN72i6exOlJkew==,iv:eeprjmvtwZYPlcJqLstv66c6grZj2ty1cf+pfT5uubM=,tag:XqguaED0wH7K3bbXmUCnsA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:RriXphqqMgMoAgopIbeGkdDkWSyqqGglnBhKgdx8NQ==,iv:ZxiHm6SoI9zbjE6l/I9sKQgC62SEgwKYOngf/n7EEVI=,tag:k+Qrb8dGzCoJMpQwnm8x9A==,type:str]
sops:
    age:
        - recipient: age1uq9nturwsx36q045qtrm85lkg8qmzpgk9srduqesxs2ahjurw53sp9rhm6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSldBVkhVL2VCdUJNR0Zv
            QWNNUmJySk9GbG5vdHN5SkVDY3R4S1BTWUVFCjJVYVhTRUdPbUI0dWFrZWxjQlV4
            NUI5cGErUzliQ0xaQll6SEJicVlmcDgKLS0tIDE1VE90dlBhREhsSStXdzRGVnc5
            MllmYXhJOFZaQkdTWjhidUNVT0pDQXMK2VNhrUeK9+lbCRi457c4Sgav922s2pR+
            4w/aFuJTtqhd56mPiptjKPoG72T+VOSAfXQ3NnGVLMIgRj3wh1Eu2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T22:42:01Z"
    mac: ENC[AES256_GCM,data:e1aEbyDhYZyHJf6KhIXLbqUqLOrQMshRVLlxaQMzMzvqQD+JJuP8epx62w0yHQZWzocTzfOK1jUCMIAuyVU/toy3S6dAJyqEEbaG2CwNUZ1S5Ifkrxl498TO311MxrtxY4qWmLRUgn+ggYKz6uQje3nNJTFJp6JRmRApcrZWgWQ=,iv:+nFx6mNy5jkHNQjIFr6pH9imiF8xNUVg4S/cklecSLY=,tag:ZHGXbaNdCua/4eP0+letwQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
