apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cloudnative-pg
  - namespace.yaml
  - b2-credentials-secret.yaml
  - postgres-cluster.yaml
  - scheduled-backup.yaml
  - commafeed-database.yaml
  - linkding-database.yaml
  - nightscout-database.yaml
  - grant-documentdb-permissions-job.yaml
