apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: speedtest
resources:
  - ../../base/speedtest
  - ingress.yaml
  - speedtest-db-secret.yaml
  - speedtest-env-secret.yaml
patchesStrategicMerge:
  - deployment-patch.yaml
