apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/speedtest
  - ingress.yaml
  - speedtest-db-secret.yaml
  - speedtest-env-secret.yaml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: speedtest
