apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
data:
  services.yaml: |
    - Bookmarks:
        - Linkding:
            icon: linkding.png
            href: https://linkding.ronaldlokers.nl
            description: Bookmark manager

    - Reading:
        - Commafeed:
            icon: commafeed.png
            href: https://commafeed.ronaldlokers.nl
            description: RSS feed reader

    - Health:
        - Nightscout:
            icon: nightscout.png
            href: https://nightscout.ronaldlokers.nl
            description: CGM remote monitoring

    - Monitoring:
        - Grafana:
            icon: grafana.png
            href: https://grafana.ronaldlokers.nl
            description: Metrics and dashboards
            widget:
              type: grafana
              url: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80
              username: "{{HOMEPAGE_VAR_GRAFANA_USER}}"
              password: "{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}"
        - Speedtest:
            icon: speedtest.png
            href: https://speedtest.ronaldlokers.nl
            description: Network speed test

    - Infrastructure:
        - Proxmox:
            icon: proxmox.png
            href: https://proxmox.lokilabs.nl
            username: "{{HOMEPAGE_VAR_PROXMOX_TOKEN}}"
            password: "{{HOMEPAGE_VAR_PROXMOX_SECRET}}"
            node: gandalf
            description: Virtualization platform
            widget:
              type: proxmox
        - Longhorn:
            icon: longhorn.png
            href: https://longhorn.ronaldlokers.nl
            description: Distributed block storage
        - pgAdmin:
            icon: pgadmin.png
            href: https://pgadmin.ronaldlokers.nl
            description: PostgreSQL admin

    - GitOps:
        - Flux:
            icon: flux-cd.png
            href: https://fluxcd.io/
            description: GitOps continuous delivery
  proxmox.yaml: |
    - gandalf:
        url: https://proxmox.lokilabs.nl
        token: "{{HOMEPAGE_VAR_PROXMOX_TOKEN}}"
        secret: "{{HOMEPAGE_VAR_PROXMOX_SECRET}}"
