apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
data:
  services.yaml: |
    - Bookmarks:
        - Linkding:
            icon: linkding.png
            href: https://linkding.ronaldlokers.nl
            description: Bookmark manager

    - Media:
        - Commafeed:
            icon: commafeed.png
            href: https://commafeed.ronaldlokers.nl
            description: RSS feed reader
        - Immich:
            icon: immich.png
            href: https://immich.ronaldlokers.nl
            description: Photo management
            widget:
              type: immich
              url: http://immich-server.immich.svc.cluster.local:2283
              key: IeLyIEuyA5bSzy2Sfotk7MFTemWg3uOQ7JdimY88
              version: 2

    - Health:
        - Nightscout:
            icon: nightscout.png
            href: https://nightscout.ronaldlokers.nl
            description: CGM remote monitoring
    - DevOps:
        - Grafana:
            icon: grafana.png
            href: https://grafana.ronaldlokers.nl
            description: Metrics and dashboards
            widget:
              type: grafana
              url: http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:80
              username: "{{HOMEPAGE_VAR_GRAFANA_USER}}"
              password: "{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}"
        - Prometheus:
            icon: prometheus.png
            href: https://prometheus.ronaldlokers.nl
            description: Metrics collection and storage
        - Ntfy:
            icon: ntfy.png
            href: https://ntfy.ronaldlokers.nl
            description: Push notifications
        - Speedtest:
            icon: speedtest-tracker.png
            href: https://speedtest.ronaldlokers.nl
            description: Network speed test
            widget:
              type: speedtest
              url: http://speedtest.speedtest.svc.cluster.local
              version: 1
        - Flux:
            icon: flux-cd.png
            href: https://fluxcd.io/
            description: GitOps continuous delivery

    - Infrastructure:
        - Proxmox:
            icon: proxmox.png
            href: https://proxmox.lokilabs.nl
            node: gandalf
            description: Virtualization platform
            widget:
              type: proxmox
              url: https://proxmox.lokilabs.nl
              username: "{{HOMEPAGE_VAR_PROXMOX_TOKEN}}"
              password: "{{HOMEPAGE_VAR_PROXMOX_SECRET}}"
        - TrueNAS:
            icon: truenas.png
            href: https://truenas.ronaldlokers.nl
            description: Network-attached storage
        - Longhorn:
            icon: longhorn.png
            href: https://longhorn.ronaldlokers.nl
            description: Distributed block storage
        - pgAdmin:
            icon: pgadmin.png
            href: https://pgadmin.ronaldlokers.nl
            description: PostgreSQL admin
        - Mikrotik:
            icon: mikrotik.png
            href: https://10.0.1.1
            description: Mikrotik Router
            widget:
              type: mikrotik
              url: https://10.0.1.1
              username: "{{HOMEPAGE_VAR_MIKROTIK_USERNAME}}"
              password: "{{HOMEPAGE_VAR_MIKROTIK_PASSWORD}}"
  proxmox.yaml: |
    - gandalf:
        url: https://proxmox.lokilabs.nl
        token: "{{HOMEPAGE_VAR_PROXMOX_TOKEN}}"
        secret: "{{HOMEPAGE_VAR_PROXMOX_SECRET}}"
