apiVersion: apps/v1
kind: Deployment
metadata:
  name: nightscout
  namespace: nightscout
spec:
  template:
    spec:
      containers:
        - name: nightscout
          env:
            - name: MONGODB_URI
              value: "mongodb://ferretdb:27017/postgres"
