apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nightscout
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-https-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - secretName: wildcard-ronaldlokers-nl-tls
      hosts:
        - nightscout.ronaldlokers.nl
  rules:
    - host: nightscout.ronaldlokers.nl
      http:
        paths:
          - backend:
              service:
                name: nightscout
                port:
                  number: 1337
            path: /
            pathType: Prefix
