apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - s3-secret.yaml
  - release.yaml
  - longhorn-node-kube-srv-1.yaml
  - longhorn-node-kube-srv-2.yaml
  - longhorn-node-kube-srv-3.yaml
