apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/network-policies
  - cert-manager
  - cloudnative-pg
  - traefik-default-cert.yaml
  - traefik-https-redirect-middleware.yaml
