apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ntfy
resources:
  - ../../base/ntfy/
  - ingress.yaml
  - ntfy-secret.yaml
patchesStrategicMerge:
  - configmap-patch.yaml
  - deployment-patch.yaml
