---
# Default deny all ingress traffic in linkding namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: linkding
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
# Default deny all egress traffic in linkding namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-egress
  namespace: linkding
spec:
  podSelector: {}
  policyTypes:
    - Egress
---
# Default deny all ingress traffic in homepage namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: homepage
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
# Default deny all egress traffic in homepage namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-egress
  namespace: homepage
spec:
  podSelector: {}
  policyTypes:
    - Egress
---
# Default deny all ingress traffic in nightscout namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: nightscout
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
# Default deny all egress traffic in nightscout namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-egress
  namespace: nightscout
spec:
  podSelector: {}
  policyTypes:
    - Egress
---
# Default deny all ingress traffic in pgadmin namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: pgadmin
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
# Default deny all egress traffic in pgadmin namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-egress
  namespace: pgadmin
spec:
  podSelector: {}
  policyTypes:
    - Egress
---
# Default deny all ingress traffic in commafeed namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: commafeed
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
# Default deny all egress traffic in commafeed namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-egress
  namespace: commafeed
spec:
  podSelector: {}
  policyTypes:
    - Egress
---
# Default deny all ingress traffic in speedtest namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: speedtest
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
# Default deny all egress traffic in speedtest namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-egress
  namespace: speedtest
spec:
  podSelector: {}
  policyTypes:
    - Egress
---
# Default deny all ingress traffic in immich namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: immich
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
# Default deny all egress traffic in immich namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-egress
  namespace: immich
spec:
  podSelector: {}
  policyTypes:
    - Egress
---
# Default deny all ingress traffic in ntfy namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: ntfy
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
# Default deny all egress traffic in ntfy namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-egress
  namespace: ntfy
spec:
  podSelector: {}
  policyTypes:
    - Egress
---
# Default deny all ingress traffic in database namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: database
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
# Default deny all egress traffic in database namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-egress
  namespace: database
spec:
  podSelector: {}
  policyTypes:
    - Egress
---
# Default deny all ingress traffic in monitoring namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: monitoring
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
# Default deny all egress traffic in monitoring namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-egress
  namespace: monitoring
spec:
  podSelector: {}
  policyTypes:
    - Egress
