apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default-deny-all.yaml
  - allow-dns.yaml
  - allow-ingress-to-apps.yaml
  - allow-apps-to-database.yaml
  - allow-monitoring.yaml
  - allow-egress-internet.yaml
  - allow-homepage-to-apps.yaml
  - allow-database-to-k8s-api.yaml
  - allow-immich-internal.yaml
  - allow-loki-to-s3.yaml
