apiVersion: v1
kind: Secret
metadata:
    name: b2-credentials
    namespace: database
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:woGwEUq0mSGN0twaIcH6+75UMW5yiBx66Q==,iv:6aAaR7m4V5dyMp507ImtZA0sDb+gKwNMimirC25C1lw=,tag:BIi4N2tUuM6c4zwJGUXmHQ==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:BO5xdMtDQ0yo6PJjuHLR5hziy7okeX5L8dA+eUFCMA==,iv:UFPfNSZB2VULLFNjdK1nXlZreVplJpIR68qR+MoPqoc=,tag:KyqKk/xhLLZO57NYTy6soQ==,type:str]
sops:
    age:
        - recipient: age1hh6cdyljk2ks5mkmxqx6g65c7a8rgndy5p2s2d7w2gvqx4h53ggqtwr7rh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVFBBSHF3cjN3S3hjWmdV
            N3lNS2hVVlhUb0xrK1Q0OU5pSXI1MXgwTUJRCmdWSlJjanRzMWRMM2RVMDJSMlNM
            TDYwTHI4K2YrTVNzVVhKdUQwek93cjAKLS0tIDhLWlMzbXlZdFAvMzAyYkpVaDh6
            QkFpczVQUHBkK0xwN3Uvay94L0F5dkEK6XFxsyjqlzLO1VT0mg0zj6FMYMeVKibo
            RC6kPAshGmzP/XGNVUMjlykj1wBLzhhAU+xTrmcfZXtFtIWYs8GTRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T22:42:03Z"
    mac: ENC[AES256_GCM,data:V5d7p82Oq9W/cVnQLTIAFxI9k3huksKTYtc7MxU1ZMmP3ibQNY3oft8P3P8COEmLF/QvvJVWdJUszLOkOIbOBVFjq+rCqbN9yZNA+SHaDatLZTxlz4DeWrIu5tw+NDoDra2Cl/wCfUf4SE8hNP3BIbCC4g6qaFK4nZrm6H3I52U=,iv:anb9w8/J85UA0YYQMKZ3ypXB4Ccq8UxH+M1L4M9V13I=,tag:lkOYqe7qHImotG4cm2rUpA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
